# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-06 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='links',
        ),
    ]
