# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-08 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0005_auto_20190908_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=89, null=True),
        ),
    ]
