# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-08 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0008_auto_20190908_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.TextField(null=True),
        ),
    ]
