# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-08 20:32
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0009_auto_20190908_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
